baseURL: https://yuqiao-andrew-leng.netlify.app/
languageCode: en-us
title: Yuqiao Leng's Website 
theme: forty
googleAnalytics: ''
disqusShortname: ''
params:
  banner:
    buttonText: Get Started
    subtitle: I shared my thoughts and works, hope that you enjoy them.
    title: Hi there, welcome to Yuqiao's website. 
  blog: {}
  contact:
    address:
      - city: London
        country: the United Kingdom
        street: Bickenhall Mansions, W1U 6BR
        title: Address
    buttonClear: Clear
    buttonSend: Send message
    email:
      - email: yleng.mam2023@london.edu
        title: Email
    enable: yes
    phone:
      - phone: (440) 7536210590 / (86) 15044087124
        title: Phone
  custom_css: []
  custom_js: []
  description: Your description
  error404:
    heading: Page couldn't be found
    text: Please visit [this page](/)
  favicon: favicon.ico
  footer:
    copyright: Company Name
    enable: yes
    quicklinks:
      - alt: HTML5 UP
        text: 'Design: '
        url: https://www.html5up.net
    social:
      - icon: fa-twitter
        label: Twitter
        url: https://twitter.com/Andreww1213
      - icon: fa-facebook
        label: Facebook
        url: https://www.facebook.com/yuqiao.leng
      - icon: fa-instagram
        label: Instagram
        url: https://www.instagram.com/andrewlengg/
      - icon: fa-github
        label: GitHub
        url: https://github.com/andrewlengg
      - icon: fa-linkedin
        label: LinkedIn
        url: https://www.linkedin.com/in/yuqiao-leng-99wmay/
  image: ''
  name: Yuqiao Leng
  navigation:
    button1:
      - name: Get Started
        url: blogs
    button2:
      - name: Log In
        url: '#'
    links:
      - name: Home
        url: '#'
      - name: Blogs
        url: blogs
      - name: Generic Blog
        url: blogs/ipsum
      - name: Elements
        url: elements.html
    menu: Menu
    subtitle: By HTML5 Up
    title: Forty
  tiles:
    enable: yes
    showcase:
      - image: IMG_3729.JPG
        #subtitle: Ipsum Dolor Sit Amet
        title: CV
        url: public/Yuqiao Leng CV.pdf
      - image: IMG_0543.jpg
        #subtitle: Feugiat Amet Tempus
        title: R Project Example
        url: blogs/Group-14-Project-final
      - image: IMG_1974.jpg
        #subtitle: Lorem Etiam Nullam
        title: Python Project Example
        url: blogs/LSTM
